### PR TITLE
Add icons for “M” (linear referencing) geometry types

### PR DESCRIPTION
**Pull request by effjot**
Show geometry icons in locator search results for geometry types with  “M” coordinate, e.g.  LINESTRINGM.

### CODE REVIEW

**Review by Gustry — APPROVED** [review]
LGTM

Note, when QGIS 3.28 will be minimum version, there is a builtin function in QGIS now https://api.qgis.org/api/classQgsIconUtils.html, I will make a patch in the plugin to use this function instead.

**Comment by Gustry** [comment]
Hum, the geometry is a string, because we get it from `... d.geometry_type, ... FROM pgmetadata.export_datasets_as_flat_table('{locale}') d`, not sure it's worth it to build the QgsMapLayer to use QgsIconUtils.

**Comment by effjot** [comment]
`return QgsIconUtils.iconForWkbType(QgsWkbTypes.parseType(geometry_type))` should do the trick, but I haven’t tested it fully yet.

**Comment by Gustry** [comment]
Thanks for checking.
I haven't tried, but just to keep notes : https://github.com/3liz/qgis-pgmetadata-plugin/pull/161

**Pull request merged**
